[package]
name = "zk-STARKLab"
version = "0.1.0"
authors = ["Tyler Maginnis <Tyler.Maginnis@perfectyourcustomer.com>"]
edition = "2018"

[dependencies]
sha1 = "^0.10"
sha2 = "^0.9"
sha3 = "^0.10"
blake2 = "^0.9"
blake3 = "^0.2"
hmac = "^0.9"
md-5 = "^0.8"
skein-hash = "^0.3"
gost94 = "0.10.4"
ripemd160 = "^0.9"
